# Generated by Django 4.2.7 on 2024-08-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_files',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
