# Generated by Django 4.2.7 on 2024-08-12 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_upload_files_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(error_messages='Please upload valid file', max_length=5, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['csv', 'xlsx'])])),
            ],
        ),
        migrations.DeleteModel(
            name='upload_files',
        ),
    ]
